Fix bedinfo for consecutive bed use
martinkadlec0/hc-tcg pull request #130
Opened 2023-04-04 21:18 UTC by NikoUY

bedInfo was being set to True even when the bed was discarded which prevented consecutive use of the bed.

2023-04-11 02:30 UTC, Sense101 requested changes
This code does nothing

2023-04-11 10:42 UTC, nikod commented
This fixes the case where your bed disappeared at the start of the turn and you added a new bed on the same turn.

Previously bedInfo was set to True when the card was discarded.
When actionEnd was called back hadBed (bedInfo) was True.
Because hadBed was True you would not be put to sleep.
Next turn the bed disappears when turnStart is called because you are not sleeping.

I tested it again and the change works, make sure to restart the server if you already tested it, if you edit the file with the server running the change won’t work, the page reloads but it won’t work, I’m probably being dumb because I have zero web dev experience, I just followed the logic and tested the change.

2023-04-11 10:45 UTC, NikoUY commented
This fixes the case where your bed disappeared at the start of the turn and you added a new bed on the same turn.

Previously bedInfo was set to True when the card was discarded.
When actionEnd was called back hadBed (bedInfo) was True.
Because hadBed was True you would not be put to sleep.
Next turn the bed disappears when turnStart is called because you are not sleeping.

I tested it again and the change works, make sure to restart the server if you already tested it, if you edit the file with the server running the change won’t work, the page reloads but it won’t work, I’m probably being dumb because I have zero web dev experience, I just followed the logic and tested the change.

2023-04-11 12:44 UTC, Sense101 commented
You're missing the point - your else if statement does exactly the same things as the if statement

2023-04-11 13:55 UTC, Sense101 commented
![image](https://user-images.githubusercontent.com/67970865/231185506-944aeb11-542d-4139-8b02-36cec010eb5c.png)
... look at it - the else if statement is exactly the same as the if - meaning nothing is changing in the flow of logic. Please explain.

2023-04-11 14:03 UTC, NikoUY commented
I don't know how else to put it, the only thing I can think of is to write some pseudo code for that case

Previously 
If not sleeping and has bed
   discard card
If has bed 
   set bedInfo to true

Now
If not sleeping and has bed 
   discard card
otherwise if sleeping (that's what fails in the first if) and has bed
  set bedInfo

What I proposed in the previous comments to make it more clear and it's what it's basically happening anyway
if not sleeping and has bed
   discard card
   set bedInfo to false
otherwise
   set bedInfo to true

2023-04-13 21:46 UTC, Sense101 commented
Looks good, thanks a lot. This likely won't make it into the game till we release a new update, but when it is, it'll be credited to you on github and discord.

2023-04-13 21:47 UTC, merged