Mending
martinkadlec0/hc-tcg pull request #194
Opened 2023-06-04 12:09 UTC by Tyrannicodin

2023-06-05 12:10 UTC, Sense101 commented
make sure to change to new mending as per spreadsheet, plus remove hooks on detach

2023-06-12 22:46 UTC, NikoUY requested changes
This card is outdated, you need to update it using the new description.

2023-06-14 19:44 UTC, Sense101 requested changes

2023-06-14 19:44 UTC, Sense101 commented on common/cards/card-plugins/single-use/mending.js
> +		])
pickOn and pickReq needs to be passed within super

2023-06-14 19:44 UTC, Sense101 commented on common/cards/card-plugins/single-use/mending.js
> +
you need the canApply method returning true, so this can be applied

2023-06-14 19:44 UTC, Sense101 commented on common/cards/card-plugins/single-use/mending.js
> +		this.pickReqs = /** @satisfies {Array<PickRequirmentT>} */ ([
no need for @ satisfies anymore, remove pls

2023-06-14 19:44 UTC, Sense101 commented on common/cards/card-plugins/single-use/mending.js
> +
you also need a canAttach method that makes sure the active hermit has an effect card - see one of niko's merged signle use cards.

2023-06-14 19:44 UTC, Sense101 commented on common/cards/card-plugins/single-use/mending.js
> +// TODO - Must work with Gemintay ability to use two single use cards per turn (should mend the first one)
With the new functionality, this should work fine, so this todo can be removed - provided you've set up canAttach correctly -see below

2023-06-16 11:24 UTC, Sense101 approved these changes
Still no canApply here, but merging anyways

2023-06-16 11:24 UTC, merged