Totem
martinkadlec0/hc-tcg pull request #203
Opened 2023-06-06 21:20 UTC by Tyrannicodin

2023-06-12 22:56 UTC, NikoUY commented on common/cards/card-plugins/effects/totem.js
>  		game.hooks.hermitDeath.tap(this.id, (recovery, deathInfo) => {
Use the afterAttack hook and this needs to be redone to work with that hook, make sure to discard the totem.

2023-06-12 22:56 UTC, NikoUY commented on common/cards/card-plugins/effects/totem.js
> +	 *
This can be removed

2023-06-15 15:45 UTC, Sense101 requested changes
One more change., then this can be merged :)

2023-06-15 15:45 UTC, Sense101 commented on common/cards/card-plugins/effects/totem.js
> +			if (!result.attack.target.row || result.attack.target.row.health > 0)
Please check explicitly that the row health is not undefined. You can also define a "row" variable which is result.attack.target.row, to keep the code cleaner.

2023-06-16 11:35 UTC, merged