Helsknight rare
martinkadlec0/hc-tcg pull request #223
Opened 2023-06-10 07:13 UTC by Benji42

2023-06-14 19:59 UTC, Sense101 reviewed
Mostly looks ok - did we confirm how this works with trident?

2023-06-14 19:59 UTC, Sense101 commented on common/cards/card-plugins/hermits/helsknight-rare.js
> +// Because of this card we can't rely elsewhere on the suCard to be in state on turnEnd hook
Is this comment accurate, or copied from another card?

2023-06-14 19:59 UTC, Sense101 commented on common/cards/card-plugins/hermits/helsknight-rare.js
> +			player.custom[this.id] = true
don't use id for custom - use the instance key.

2023-06-14 19:59 UTC, Sense101 commented on common/cards/card-plugins/hermits/helsknight-rare.js
> +				if (coinFlip[0] == 'heads')
This is just semantic, but as this is too long to fit on one line please add {} for this if

2023-06-17 19:38 UTC, NikoUY commented on common/cards/card-plugins/hermits/helsknight-rare.js
> +					'If opponent uses a single use effect card on their next turn, they must flip acoin. If heads, you take the card after its effect is applied and add it to your hand.',
you wrote "acoin" instead of "a coin"

2023-06-17 19:42 UTC, NikoUY requested changes
This should only apply for 1 turn, right now if the opponent does not attack the effect will stay active, you should use turnOver to get rid of the custom value.

2023-06-17 19:53 UTC, NikoUY requested changes

2023-06-17 19:53 UTC, NikoUY commented on common/cards/card-plugins/hermits/helsknight-rare.js
> +						player.hand.push(otherPlayer.board.singleUseCard)
onDetach and the onDetach hooks should be called before removing the single use card, you can use moveCardToHand, I added it on #264.

2023-06-18 18:11 UTC, merged