Golden Axe
martinkadlec0/hc-tcg pull request #235
Opened 2023-06-13 03:58 UTC by NikoUY

2023-06-14 19:12 UTC, Sense101 requested changes
Just gonna point out - this new implementation is wayyy worse than the last, which is not our fault, but I might change it back to the old implementation.

However, as it is at the moment, this needs to be using the new power system, rather than checking if the item card is rare.

2023-06-14 23:21 UTC, NikoUY commented
Any reason why getEnergy needs game, instance and CardPos?, that seems kinda overkill, anyways, it should be done.

2023-06-15 12:32 UTC, Sense101 commented on server/utils/index.js
> +		total += cardInfo.getEnergy(game, itemCard.cardInstance, pos)
how are you adding an array to a number here??

2023-06-16 09:16 UTC, Sense101 approved these changes
This is good now, but please enable a linter for vscode, so you get errors for things like that.

2023-06-16 09:16 UTC, merged