Backend changes needed for the new Advent of TCG cards
martinkadlec0/hc-tcg pull request #404
Opened 2023-11-12 22:27 UTC by Benji42

2023-11-12 22:41 UTC, Benji42 commented
damn, that's a lot of commits

2023-11-13 09:59 UTC, Sense101 commented
Just so I'm clear this is the big pr without the actual advent cards? So this includes the new ailment system?

2023-11-14 10:45 UTC, Sense101 requested changes
This has not got the fixes @Tyrannicodin added to the other pr, what we need is a pr with those changes, but without the new cards

2023-11-14 21:13 UTC, Sense101 approved these changes

2023-11-14 21:13 UTC, merged