Stacked cards
martinkadlec0/hc-tcg pull request #79
Opened 2023-02-27 20:59 UTC by RoyaLProg

Not the cleanest of code I admit BUT it does his jobs, could clean it after !

**IMPORTANT** when using stacked card list I do not use the "<animated.div>" !

Should work with no problem (test needed !)

in CSS : just making each card stack on top of the one above + makign card over 3 desapear (for extra large screen to not have random card seen a the bottom)

In card-list.tsx :

+ adding "stack" prameter defaulted at false
+ creating "StackCardOutput" (does the sane thing as "CardOutput" but with a div over the cards taht goes together)

(on good branch this time x) )

2023-02-27 21:02 UTC, RoyaLProg commented
As what we said on the discord server it does look nicer than having the same card multiple time + reduce the potential need of scrolling

2023-02-27 22:01 UTC, martinkadlec0 requested changes

2023-02-27 22:01 UTC, martinkadlec0 commented on client/src/components/card-list/card-list.tsx
> +				const cardlist = []
camelcase

2023-02-27 22:01 UTC, martinkadlec0 commented on client/src/components/card-list/card-list.tsx
> +				for (let i = 0; i < cardInstances.length; i++) {
map + filter instead?

2023-02-27 22:01 UTC, martinkadlec0 commented on client/src/components/card-list/card-list.tsx
> +	if (stack === true)
As far as I can see only the output variable differs, why not `{stack ? cardsStackedOutput : cardsOutput}` instead of duplicating the whole thing?

2023-02-27 22:11 UTC, RoyaLProg commented on client/src/components/card-list/card-list.module.css
> +.stackcard div:nth-child(3) {
i could maybe do it on SASS but no tin CSS ;/

2023-02-27 22:16 UTC, martinkadlec0 commented on client/src/components/card-list/card-list.module.css
> +.stackcard div:nth-child(3) {
Perhaps we can hide +3 cards somehow? And just indicate there is more?

2023-02-27 22:19 UTC, RoyaLProg commented on client/src/components/card-list/card-list.module.css
> +.stackcard div:nth-child(3) {
Should be doable, i'll check for that

2023-02-27 22:20 UTC, RoyaLProg commented on client/src/components/card-list/card-list.tsx
> +		const stack: Map<string, CardT[]> = new Map()
Maps are basics objects, and make this whole process easier ^^'

2023-02-27 22:24 UTC, martinkadlec0 commented on client/src/components/card-list/card-list.tsx
> +		const stack: Map<string, CardT[]> = new Map()
Not really, the syntax is just tiny bit different. I don't use Maps anywhere else, so again I'd like to stick with normal objects for consistency reasons.

2023-02-27 22:26 UTC, RoyaLProg commented on client/src/components/card-list/card-list.tsx
> +		const stack: Map<string, CardT[]> = new Map()
i will try other ways

2023-02-27 22:34 UTC, RoyaLProg commented on client/src/components/card-list/card-list.tsx
> +		const stack: Map<string, CardT[]> = new Map()
I maybe can do it by modifying the card object itself

making the cardInstance variable an array

2023-02-27 23:34 UTC, RoyaLProg commented on client/src/components/card-list/card-list.module.css
> +.stackcard div:nth-child(3) {
as +3 cards are already hided, what type of indicator would be the best ?

2023-02-27 23:35 UTC, RoyaLProg commented
almost done, just need the indicator for +3 cards ( is till dont know what to use)

2023-02-27 23:44 UTC, RoyaLProg commented
![image](https://user-images.githubusercontent.com/63088010/221714747-8592bb13-d19a-4571-82b6-75da30ad1747.png)
what do you thing about a little badge like this ?

2023-02-28 00:41 UTC, RoyaLProg commented
@martinkadlec0 are you ok with % in css positon or do you want me to make them in px/em ?

2023-03-01 21:25 UTC, RoyaLProg commented
Should be enought

2023-04-21 16:59 UTC, Sense101 commented
Can you rebase this onto the latest dev? The plan is to start working on the game screen soon so this will be helpful

2023-05-07 00:00 UTC, RoyaLProg commented
damn completly forgot about this ... still needed ?

2023-07-10 15:05 UTC, closed without merging